#!/bin/sh

#build the POP plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"POP\ plugin\" -c netfunc.c popfunc.c plg_common.c plg_pop.c -o mtc_pop.o
gcc -shared -Wl,-soname,mtc_pop.so.1 -g -o mtc_pop.so.1.0.1 mtc_pop.o -lc

#build the APOP plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"APOP\ plugin\" -DMTC_USE_SSL -c netfunc.c popfunc.c plg_common.c plg_apop.c -o mtc_apop.o
gcc -shared -Wl,-soname,mtc_apop.so.1 -g -o mtc_apop.so.1.0.1 mtc_apop.o -lc -lcrypto -lssl

#build the POP CRAM-MD5 plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"POP\ CRAM-MD5\ plugin\" -DMTC_USE_SASL -c netfunc.c popfunc.c plg_common.c plg_popcram.c -o mtc_popcram.o
gcc -shared -Wl,-soname,mtc_popcram.so.1 -g -o mtc_popcram.so.1.0.1 mtc_popcram.o -lc -lgsasl

#build the POP SSL/TLS plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"POP\ SSL/TLS\ plugin\" -DMTC_USE_SSL -c netfunc.c popfunc.c plg_common.c plg_popssl.c -o mtc_popssl.o
gcc -shared -Wl,-soname,mtc_popssl.so.1 -g -o mtc_popssl.so.1.0.1 mtc_popssl.o -lc -lcrypto -lssl

#build the IMAP plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"IMAP\ plugin\" -c netfunc.c imapfunc.c plg_common.c plg_imap.c -o mtc_imap.o
gcc -shared -Wl,-soname,mtc_imap.so.1 -g -o mtc_imap.so.1.0.1 mtc_imap.o -lc

#build the IMAP CRAM-MD5 plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"IMAP\ CRAM-MD5\ plugin\" -DMTC_USE_SASL -c netfunc.c imapfunc.c plg_common.c plg_imapcram.c -o mtc_imapcram.o
gcc -shared -Wl,-soname,mtc_imapcram.so.1 -g -o mtc_imapcram.so.1.0.1 mtc_imapcram.o -lc -lgsasl

#build the IMAP SSL/TLS plugin
gcc -fPIC -ansi -pedantic -W -g -Wall -DPACKAGE=\"IMAP\ SSL/TLS\ plugin\" -DMTC_USE_SSL -c netfunc.c imapfunc.c plg_common.c plg_imapssl.c -o mtc_imapssl.o
gcc -shared -Wl,-soname,mtc_imapssl.so.1 -g -o mtc_imapssl.so.1.0.1 mtc_imapssl.o -lc -lcrypto -lssl

#build the app
#gcc -g -ansi -pedantic -Wall -W netfunc.c popfunc.c plg_common.c plgtest.c -ldl -o plugintest
gcc -g -ansi -pedantic -Wall -W plgtest.c -ldl -o plugintest
